version: "3.0"

networks:
  alg-net:

services:
  alg-server:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    image: alg-server:latest
    ports:
      - "5000:5000"
    environment:
      ALG_SERVER_PORT: 5000
      ALG_ENV: dev
    networks:
      - alg-net
  alg-agent-1:
    build:
      context: .
      dockerfile: ./Dockerfile.agent
    image: alg-agent:latest
    ports:
      - "5001:5000"
    environment:
      ALG_AGENT_ID: agent-1
      ALG_AGENT_PORT: 5000
      ALG_SERVER_ADDR: http://alg-server:5000
      ALG_AGENT_ADDR: http://alg-agent-1:5000
      ALG_ENV: dev
    networks:
      - alg-net
    depends_on:
      - alg-server
  alg-agent-2:
    image: alg-agent:latest
    ports:
      - "5002:5000"
    environment:
      ALG_AGENT_ID: agent-2
      ALG_AGENT_PORT: 5000
      ALG_SERVER_ADDR: http://alg-server:5000
      ALG_AGENT_ADDR: http://alg-agent-2:5000
      ALG_ENV: prod
    networks:
      - alg-net
    depends_on:
      - alg-server
  alg-agent-3:
    image: alg-agent:latest
    ports:
      - "5003:5000"
    environment:
      ALG_AGENT_ID: agent-3
      ALG_AGENT_PORT: 5000
      ALG_SERVER_ADDR: http://alg-server:5000
      ALG_AGENT_ADDR: http://alg-agent-3:5000
      ALG_ENV: prod
    networks:
      - alg-net
    depends_on:
      - alg-server
  alg-agent-4:
    image: alg-agent:latest
    ports:
      - "5004:5000"
    environment:
      ALG_AGENT_ID: agent-4
      ALG_AGENT_PORT: 5000
      ALG_SERVER_ADDR: http://alg-server:5000
      ALG_AGENT_ADDR: http://alg-agent-4:5000
      ALG_ENV: prod
    networks:
      - alg-net
    depends_on:
      - alg-server
