FROM python:3.8.5-buster

EXPOSE 5000

ENV PYTHONPATH "."

RUN mkdir /app
WORKDIR /app

COPY requirements.txt /app/
RUN pip3 install -r requirements.txt

COPY ./agent/lib.py ./agent/agent.py /app/

CMD ["python", "agent.py"]
